version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: deployment_script/stop_server
      timeout: 300
      runas: root
      
  BeforeInstall:
    - location: deployment_script/before_install
      timeout: 300
      runas: root

  AfterInstall:
    - location: deployment_script/after_install
      timeout: 300
      runas: root

  ApplicationStart:
    - location: deployment_script/start_server
      timeout: 300
      runas: root

  ValidateService:
    - location: deployment_script/validate_service
      timeout: 300
      runas: root
  
