version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 240068248627.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=240068248627.dkr.ecr.ap-south-1.amazonaws.com/oodles-test
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t oodles-test:latest .
      - docker tag oodles-test:latest 240068248627.dkr.ecr.ap-south-1.amazonaws.com/oodles-test:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 240068248627.dkr.ecr.ap-south-1.amazonaws.com/oodles-test:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
